trigger: none

resources:
  repositories:
  - repository: devops
    type: git
    name: Automation/devops-templates

parameters:
- name: ENVIRONMENT
  displayName: Environment to Destroy
  type: string
  default: dev
  values:
  - dev
  - prod

variables:
- group: PolicyAnalyzAIInfra

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: PublishTerraform
  displayName: Publish Terraform
  jobs:
  - job: PublishTerraform
    displayName: Publish Terraform
    steps:
    - publish: $(Build.SourcesDirectory)/cicd/tf
      artifact: tf

- stage: ApproveProdDestroy
  displayName: Approve PROD Destroy
  dependsOn: PublishTerraform
  condition: and(succeeded(), eq('${{ parameters.ENVIRONMENT }}', 'prod'))
  jobs:
  - template: utils/templates/stages/stage-approve-and-prepare-release.yml@devops
    parameters:
      STAGE_DEPENDENCY: [ PublishTerraform ]
      STAGE_DISPLAY_NAME: "Approve PROD Destroy"
      TESTERS_EMAILS: $(TESTERS_EMAILS)
      STAGE_NAME: "ApproveProdDestroy"

- stage: DestroyDev
  displayName: Destroy DEV Infrastructure
  dependsOn: PublishTerraform
  condition: and(succeeded(), eq('${{ parameters.ENVIRONMENT }}', 'dev'))
  jobs:
  - template: templates/job-destroy-infra.yml
    parameters:
      TERRAFORM_ARTIFACT: tf
      ENVIRONMENT_NAME: ci
      AZURE_SUBSCRIPTION: $(AZURE_SUBSCRIPTION)
      TF_STATE_ACCOUNT: paiv2stateacc
      TF_STATE_RESOURCE_GROUP: polanalyai-state-rg
      TF_ENV: dev
      STORAGE_CONTAINER_PREFIX: polanalyai-infra

- stage: DestroyProd
  displayName: Destroy PROD Infrastructure
  dependsOn: ApproveProdDestroy
  condition: and(succeeded(), eq('${{ parameters.ENVIRONMENT }}', 'prod'))
  jobs:
  - template: templates/job-destroy-infra.yml
    parameters:
      TERRAFORM_ARTIFACT: tf
      ENVIRONMENT_NAME: prod
      AZURE_SUBSCRIPTION: $(AZURE_SUBSCRIPTION)
      TF_STATE_ACCOUNT: paiv2stateacc
      TF_STATE_RESOURCE_GROUP: polanalyai-state-rg
      TF_ENV: prod
      STORAGE_CONTAINER_PREFIX: polanalyai-infra
