trigger: none

resources:
  repositories:
  - repository: devops
    type: git
    name: Automation/devops-templates

parameters:
- name: DEPLOY
  displayName: Force Deploy?
  type: boolean
  default: false

variables:
- name: buildConfiguration
  value: "Release"
- name: DEPLOY
  ${{ if or( eq(parameters.DEPLOY, 'true'), eq(variables['Build.SourceBranchName'], 'main')) }}:
    value: true
- name: TAG
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    value: "$(Build.BuildNumber)"
  ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
    value: "$(Build.BuildNumber)-preview"

- group: PolicyAnalyzAIInfra

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: BuildPushImages
  displayName: Build & push images
  jobs:
  - job: PublishTerraform
    displayName: Publish Terraform
    condition: eq(variables['DEPLOY'], 'true')
    steps:
    - publish: $(Build.SourcesDirectory)/cicd/tf
      artifact: tf

- stage: DeployBaseInfraToCI
  displayName: Deploy Base Infra CI
  condition: and(succeeded(), eq(variables['DEPLOY'], 'true'))
  jobs:
  - template: templates/job-deploy-infra.yml
    parameters:
      TERRAFORM_ARTIFACT: tf
      ENVIRONMENT_NAME: ci
      AZURE_SUBSCRIPTION: $(AZURE_SUBSCRIPTION)
      TF_STATE_ACCOUNT: paiv2stateacc
      TF_STATE_RESOURCE_GROUP: polanalyai-state-rg
      TF_ENV: dev
      STORAGE_CONTAINER_PREFIX: polanalyai-infra

- template: utils/templates/stages/stage-approve-and-prepare-release.yml@devops
  parameters:
    STAGE_DEPENDENCY: [ DeployBaseInfraToCI ]
    STAGE_DISPLAY_NAME: "Approve Prod"
    TESTERS_EMAILS: $(TESTERS_EMAILS)
    STAGE_NAME: "ApproveProd"

- stage: DeployBaseInfraToPROD
  displayName: Deploy Base Infra PROD
  condition: and(succeeded(), eq(variables['DEPLOY'], 'true'))
  jobs:
  - template: templates/job-deploy-infra.yml
    parameters:
      TERRAFORM_ARTIFACT: tf
      ENVIRONMENT_NAME: prod
      AZURE_SUBSCRIPTION: $(AZURE_SUBSCRIPTION)
      TF_STATE_ACCOUNT: paiv2stateacc
      TF_STATE_RESOURCE_GROUP: polanalyai-state-rg
      TF_ENV: prod
      STORAGE_CONTAINER_PREFIX: polanalyai-infra
